# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-02 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdog',
            name='amount_changed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpref',
            name='amount_changed',
            field=models.IntegerField(default=0),
        ),
    ]
